import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { gilroyRegular, gilroyMedium, gilroySemiBold, gilroyBold } from "@/components/hero/fonts";
import { Navbar } from "@/components/navbar/Navbar";
import { SiteFooterWrapper } from "@/components/site-footer/SiteFooterWrapper";
import { SmoothScroll } from "@/components/SmoothScroll";
import { getGlobalSettings } from "@/lib/strapi";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ambient",
  description: "Generated by Ambient",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let settings: any = null;
  try {
    settings = await getGlobalSettings<any>();
  } catch {
    settings = null;
  }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${gilroyRegular.variable} ${gilroyMedium.variable} ${gilroySemiBold.variable} ${gilroyBold.variable} h-full overflow-x-clip scroll-smooth antialiased`}
      data-scroll-behavior="smooth"
    >
      <body className="flex min-h-full flex-col overflow-x-clip bg-black">
        <SmoothScroll>
          <Navbar data={settings?.header} brandData={settings?.brand} />
          {children}
          <SiteFooterWrapper data={settings?.footer} brandData={settings?.brand} newsletterData={settings?.newsletter} />
        </SmoothScroll>
      </body>
    </html>
  );
}
