import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { gilroyRegular, gilroyMedium, gilroySemiBold, gilroyBold } from "@/components/hero/fonts";
import { Navbar } from "@/components/navbar/Navbar";
import { SiteFooter } from "@/components/site-footer/SiteFooter";
import { SmoothScroll } from "@/components/SmoothScroll";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ambient",
  description: "Generated by Ambient",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${gilroyRegular.variable} ${gilroyMedium.variable} ${gilroySemiBold.variable} ${gilroyBold.variable} h-full overflow-x-clip scroll-smooth antialiased`}
    >
      <body className="flex min-h-full flex-col overflow-x-clip bg-black">
        <SmoothScroll>
          <Navbar />
          {children}
          <SiteFooter />
        </SmoothScroll>
      </body>
    </html>
  );
}
